services:
  servizio.caching:
    class: iceDevelop\LayoutBundle\Entity\Caching
  parameters_class:
      class: iceDevelop\LayoutBundle\Entity\Parameters
      arguments: ["%progetto_intranet%","%ws_sezioni_intranet%","%url_toolkit%"]
